name: Publish to github pages

on:
  push:
    branches:
      - 'master'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      
      - name: disable jekyll
        run: touch ./page/.nojekyll

      - name: Publish to github pages
        uses: rayluo/github-pages-overwriter@v1.2
        with:
          source-directory: page
          target-branch: gh_pages